require("dotenv").config();
const express=require("express");
const cors=require("cors");
const helmet=require("helmet");
const morgan=require("morgan");
const rateLimit=require("express-rate-limit");
const initializeDatabase=require("./config/initDatabase");
const authRoutes=require("./routes/authRoutes");
const cryptoRoutes=require("./routes/cryptoRoutes");
const portfolioRoutes=require("./routes/portfolioRoutes");
initializeDatabase();
const app=express();
const PORT=process.env.PORT||5000;
app.use(helmet({crossOriginResourcePolicy:false}));
app.use(cors({origin:process.env.CLIENT_URL||"http://localhost:3000",credentials:true}));
app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use(morgan("dev"));
app.use("/api",rateLimit({windowMs:15*60*1000,max:200,standardHeaders:true,legacyHeaders:false}));
app.get("/",(req,res)=>res.json({success:true,application:"CryptoPulse",message:"CryptoPulse Backend API is running",database:"SQLite",version:"1.0.0"}));
app.get("/api/health",(req,res)=>res.json({success:true,status:"ok",database:"SQLite",timestamp:new Date().toISOString()}));
app.use("/api/auth",authRoutes);
app.use("/api/crypto",cryptoRoutes);
app.use("/api/portfolio",portfolioRoutes);
app.use((req,res)=>res.status(404).json({success:false,message:"API route not found"}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({success:false,message:"Internal Server Error"})});
app.listen(PORT, "0.0.0.0", () => {
    console.log(`CryptoPulse API running on port ${PORT}`);
});